### ISSUE TITLE
Add the ability to work with MySql

### ISSUE THREAD

**Issue by k0rsakov** [k0rsakov/connectors_to_databases#20]

**Comment by Marsh-sudo** [comment]
can you elaborate more on this issue kindly

**Comment by k0rsakov** [comment]
@Marsh-sudo Hi.
No problem.

You need to create a class inherited from BaseOperator. 

Change `_authorization_database` to connect to MySQL. 

Implement simple tests to test connectivity, create a table, delete a table, and insert data into a table. As a basis , you can take `test_module_postgresql.py`

**Comment by Marsh-sudo** [comment]
I can try to help you out with the issue

**Comment by k0rsakov** [comment]
@Marsh-sudo Hi.
Glad to hear it.

Make a fork and good luck :)

If you have any questions, write.

**Comment by k0rsakov** [comment]
@Marsh-sudo Hi.

Will you be able to complete this issue or can I take it to work?

**Comment by Marsh-sudo** [comment]
You can take it, I am so busy haven't managed to work on it lately....sorry for the inconvenience

**Comment by k0rsakov** [comment]
> You can take it, I am so busy haven't managed to work on it lately....sorry for the inconvenience

It's not a big deal. Thanks for the warning.
