### ISSUE TITLE
Add abstractmethod in BaseOperator

### ISSUE THREAD

**Issue by k0rsakov** [k0rsakov/connectors_to_databases#24]
Add abstractmethod in BaseOperator for method _authorization_database

**Comment by rajivsunar07** [comment]
can you elaborate more on this please.

**Comment by k0rsakov** [comment]
@rajivsunar07 Hi. Yes, of course, no problem.

In my implementation, there is an abstract class `BaseOperator`, from which all further classes are inherited.

There is a `_authorization_database` method in the `BaseOperator` class, which is also abstract.

It needs to be wrapped with the abstract method decorator so that it can be redefined in future classes.

More details about abstractmethod are described here https://docs.python.org/3/library/abc.html

**Comment by k0rsakov** [comment]
#25
